CastAI agent chart
castai/official-addons pull request #34
Opened 2021-11-08 10:58 UTC by matas-cast

CastAI agent as public helm chart

2021-11-09 09:46 UTC, r0kas commented on charts/castai-agent/Chart.yaml
> +  "cast.ai/includes-namespace": "true"
Why this annotation is needed? It's something that is present on current chart?

2021-11-09 09:55 UTC, r0kas commented
How did you ensure the chart works as the original one?
It would be perfect to generate both and compare the diff.

2021-11-09 14:14 UTC, matas-cast commented
> How did you ensure the chart works as the original one? It would be perfect to generate both and compare the diff.

ran `helm template` with same value file, received identical hash

2021-11-10 09:45 UTC, r0kas requested changes

2021-11-10 10:49 UTC, matas-cast commented on charts/castai-agent/values.yaml
> +cvpaEnabled: true
Agree, although hard to say if it's likely that we'll need it, but true that it would make life easier in the future so added the change

2021-11-10 10:56 UTC, matas-cast commented on charts/castai-agent/templates/cvpa-configmap.yaml
> +{{- if .Values.cvpaEnabled }}
Agreed, changed to clusterVPAEnabled

2021-11-10 11:20 UTC, r0kas commented on charts/castai-agent/values.yaml
> +cvpaEnabled: true
Can't see the change :)

2021-11-10 11:21 UTC, r0kas approved these changes
👍

2021-11-10 11:28 UTC, merged